#!/bin/zsh
echo -e "${fg[green]}$0${reset_color} --> cd $hexo_path" &&
builtin cd $hexo_path && 
echo -e "${fg[green]}$0${reset_color} --> hexo clean" &&
hexo clean &&
echo -e "${fg[green]}$0${reset_color} --> hexo g" &&
hexo g &&
echo -e "${fg[green]}$0${reset_color} --> hexo d" &&
hexo d &&
echo -e "${fg[green]}$0${reset_color} --> upload" &&
$hexo_path/source/tools/upload
echo -e "${fg[green]}$0${reset_color} --> hexo s" &&
hexo d &&

