#!/bin/zsh
echo -e "${fg[green]}$0${reset_color} --> cd $hexo_path" &&
builtin cd $hexo_path && 
echo -e "${fg[green]}$0${reset_color} --> hexo d -g" &&
hexo d -g -silent &&
echo -e "${fg[green]}$0${reset_color} --> upload" &&
$hexo_path/source/tools/upload

