#!/bin/zsh
echo -e "${fg[green]}$0${reset_color} --> git add $HOME/Workspace/hexo${reset_color}" &&
git add $HOME/Workspace/hexo &&
tim=$(date +"%F %T")
git commit -m "$tim" &&
echo -e "${fg[green]}$0${reset_color} --> git push -u origin master${reset_color}" &&
git push -u origin master
