#!/bin/zsh
msg="$(date +'%F %T')$*"
echo -e "${fg[green]}$0${reset_color} --> git add $hexo_path${reset_color}" &&
git add $hexo_path &&
git commit -m "$msg" &&
echo -e "${fg[green]}$0${reset_color} --> git push -u origin master${reset_color}" &&
git push -u origin master
